export const GET_INITIAL_FOOD_SUCCESS = 'GET_INITIAL_FOOD_SUCCESS';
export const GET_INITIAL_FOOD_FAIL = 'GET_INITIAL_FOOD_FAIL';

export const SEARCH_QUERY = 'SEARCH_QUERY';
export const SEARCH_FOOD_START = 'SEARCH_FOOD_START';
export const SEARCH_FOOD_SUCCESS = 'SEARCH_FOOD_SUCCESS';
export const SEARCH_FOOD_FAIL = 'SEARCH_FOOD_FAIL';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const IS_ADDED_TO_CART = 'IS_ADDED_TO_CART';

export const LOGIN_INPUT_CHANGE = 'LOGIN_INPUT_CHANGE';
export const SIGNUP_INPUT_CHANGE = 'SIGNUP_INPUT_CHANGE';