export const GET_INITIAL_FOOD_SUCCESS = 'GET_INITIAL_FOOD_SUCCESS';

export const SEARCH_QUERY = 'SEARCH_QUERY';
export const SEARCH_FOOD_START = 'SEARCH_FOOD_START';
export const SEARCH_FOOD_SUCCESS = 'SEARCH_FOOD_SUCCESS';
export const SEARCH_FOOD_FAIL = 'SEARCH_FOOD_FAIL';

export const TOGGLE_CART_UI = 'TOGGLE_CART_UI';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const IS_ADDED_TO_CART = 'IS_ADDED_TO_CART';
export const UPDATE_ITEM_COUNT = 'UPDATE_ITEM_COUNT';
export const CLEAR_CART = 'CLEAR_CART';

export const AUTH_STATE_CHANGED = 'AUTH_STATE_CHANGED';
export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH';
