export const GET_INITIAL_FOOD_SUCCESS = 'GET_INITIAL_FOOD_SUCCESS';

export const SEARCH_QUERY = 'SEARCH_QUERY';
export const SEARCH_FOOD_START = 'SEARCH_FOOD_START';
export const SEARCH_FOOD_SUCCESS = 'SEARCH_FOOD_SUCCESS';
export const SEARCH_FOOD_FAIL = 'SEARCH_FOOD_FAIL';

export const TOGGLE_CART_UI = 'TOGGLE_CART_UI';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const IS_ADDED_TO_CART = 'IS_ADDED_TO_CART';
export const UPDATE_ITEM_COUNT = 'UPDATE_ITEM_COUNT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH';
